version: '3'

services:
  node:
    image: node:latest
    volumes:
      - .:/app
      - ./node_modules/:/app/node_modules
    working_dir: /app
    ports:
      - 3000:3000
    entrypoint: bash -c "npm install && npm run start"
